name: CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  create-issue:
    name: Create deploy tracking issue
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v4
      with:
        script: |
            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `${context.ref} being deployed`,
              body: `ref: ${context.ref}\nsha: ${context.sha}\nactor: ${context.actor}`,
            })

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: hashtagchris
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}
        repository: hashtagchris/binary-json-formatter-fork
        tags: latest
        
