name: CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: hashtagchris
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}
        repository: hashtagchris/binary-json-formatter-fork
        tags: latest
        
  create-deploy-issue:
    name: Create deploy tracking issue
    needs: [build-and-deploy]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v4
      with:
        script: |
            await github.issues.createIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `${context.ref} deployed by ${context.actor}`,
              body: `SHA: ${context.sha}`,
            })
