name: issue_comment
on:
  issue_comment:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: cat ${{ github.event.issue.number }}
      - uses: actions/checkout@v2
        with:
          ref: "refs/pulls/merge/${{ github.event.issue.number }}"
