name: Print secrets and use environment
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  repo-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the actor
        run: echo $GITHUB_ACTOR
      - name: Echo a repository secret
        run: echo ${{ secrets.TEST_REPO_SECRET }} | rev

  env-secret:
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - name: Echo the actor
        run: echo $GITHUB_ACTOR
      - name: Echo an environment secret
        run: echo ${{ secrets.TEST_ENV_SECRET }} | rev
